// src/packages/sdk/pynomaly-js-sdk/src/components/DetectorList.vue
<!--
  Detector List Component (Vue)
  
  Vue component for displaying and managing a list of anomaly detectors
  with pagination, filtering, and selection capabilities.
-->

<template>
  <div :class="`pynomaly-detector-list ${className}`">
    <!-- Error State -->
    <div v-if="error" class="error-container">
      <div class="error-message">
        <h3>Error Loading Detectors</h3>
        <p>{{ error.message }}</p>
        <div class="error-actions">
          <button @click="clearError" class="btn-secondary">
            Dismiss
          </button>
          <button @click="refresh" class="btn-primary">
            Retry
          </button>
        </div>
      </div>
    </div>

    <template v-else>
      <!-- Header -->
      <div class="detector-list-header">
        <div class="header-info">
          <h2>Detectors</h2>
          <span class="total-count">{{ total }} total</span>
        </div>
        <div class="header-actions">
          <button 
            @click="refresh" 
            :disabled="isLoading"
            class="btn-secondary"
          >
            {{ isLoading ? 'Loading...' : 'Refresh' }}
          </button>
        </div>
      </div>

      <!-- Filters -->
      <div v-if="filters" class="detector-filters">
        <span v-if="filters.algorithmName" class="filter-tag">
          Algorithm: {{ filters.algorithmName }}
        </span>
        <span 
          v-for="tag in filters.tags" 
          :key="tag" 
          class="filter-tag"
        >
          Tag: {{ tag }}
        </span>
      </div>

      <!-- Loading State -->
      <div v-if="isLoading && detectors.length === 0" class="loading-container">
        <div class="loading-spinner"></div>
        <p>Loading detectors...</p>
      </div>

      <!-- Empty State -->
      <div v-else-if="!isLoading && detectors.length === 0" class="empty-state">
        <div class="empty-icon">🔍</div>
        <h3>No Detectors Found</h3>
        <p>
          {{ filters ? 
            'No detectors match your current filters.' : 
            'No detectors have been created yet.'
          }}
        </p>
      </div>

      <!-- Detector Grid -->
      <template v-else>
        <div class="detector-grid">
          <div
            v-for="detector in detectors"
            :key="detector.id"
            class="detector-card"
            @click="handleDetectorClick(detector)"
            @keydown="handleKeyDown($event, detector)"
            role="button"
            tabindex="0"
          >
            <div class="detector-header">
              <h3 class="detector-name">{{ detector.name }}</h3>
              <span :class="`detector-status ${detector.is_fitted ? 'trained' : 'untrained'}`">
                {{ detector.is_fitted ? 'Trained' : 'Untrained' }}
              </span>
            </div>
            
            <div class="detector-info">
              <div class="info-item">
                <label>Algorithm:</label>
                <span>{{ detector.algorithm_name }}</span>
              </div>
              <div class="info-item">
                <label>Contamination Rate:</label>
                <span>{{ (detector.contamination_rate * 100).toFixed(1) }}%</span>
              </div>
              <div v-if="detector.description" class="info-item">
                <label>Description:</label>
                <span class="description">{{ detector.description }}</span>
              </div>
            </div>

            <div v-if="detector.tags?.length" class="detector-tags">
              <span 
                v-for="tag in detector.tags" 
                :key="tag" 
                class="tag"
              >
                {{ tag }}
              </span>
            </div>

            <div class="detector-meta">
              <span class="created-date">
                Created: {{ formatDate(detector.created_at) }}
              </span>
            </div>
          </div>
        </div>

        <!-- Pagination -->
        <div v-if="total > pageSize" class="pagination">
          <button
            @click="previousPage"
            :disabled="!hasPrevious || isLoading"
            class="pagination-btn"
          >
            Previous
          </button>

          <div class="page-numbers">
            <button
              v-for="pageNum in pageNumbers"
              :key="pageNum"
              @click="goToPage(pageNum)"
              :disabled="isLoading"
              :class="`page-btn ${pageNum === page ? 'active' : ''}`"
            >
              {{ pageNum }}
            </button>
          </div>

          <button
            @click="nextPage"
            :disabled="!hasNext || isLoading"
            class="pagination-btn"
          >
            Next
          </button>
        </div>

        <!-- Page Info -->
        <div class="page-info">
          Showing {{ Math.min((page - 1) * pageSize + 1, total) }} to
          {{ Math.min(page * pageSize, total) }} of {{ total }} detectors
        </div>
      </template>
    </template>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
import { PynomalyClient } from '../core/client';
import { DetectorListProps } from '../types';

interface Props extends DetectorListProps {
  client: PynomalyClient;
  pageSize?: number;
  className?: string;
}

const props = withDefaults(defineProps<Props>(), {
  pageSize: 20,
  className: ''
});

const emit = defineEmits<{
  'detector-select': [detector: any];
}>();

// Reactive state
const detectors = ref<any[]>([]);
const total = ref(0);
const page = ref(1);
const hasNext = ref(false);
const hasPrevious = ref(false);
const isLoading = ref(false);
const error = ref<any>(null);

// Computed properties
const pageNumbers = computed(() => {
  const totalPages = Math.ceil(total.value / props.pageSize);
  const current = page.value;
  const delta = 2; // Number of pages to show on each side of current page
  
  const pages: number[] = [];
  const start = Math.max(1, current - delta);
  const end = Math.min(totalPages, current + delta);
  
  for (let i = start; i <= end; i++) {
    pages.push(i);
  }
  
  return pages;
});

// Methods
const loadDetectors = async () => {
  if (!props.client) return;
  
  isLoading.value = true;
  error.value = null;
  
  try {
    const options = {
      page: page.value,
      pageSize: props.pageSize,
      algorithmName: props.filters?.algorithmName,
      tags: props.filters?.tags
    };
    
    const response = await props.client.dataScience.listDetectors(options);
    
    detectors.value = response.items;
    total.value = response.total;
    hasNext.value = response.hasNext;
    hasPrevious.value = response.hasPrevious;
  } catch (err) {
    error.value = err;
  } finally {
    isLoading.value = false;
  }
};

const handleDetectorClick = (detector: any) => {
  emit('detector-select', detector);
};

const handleKeyDown = (event: KeyboardEvent, detector: any) => {
  if (event.key === 'Enter' || event.key === ' ') {
    handleDetectorClick(detector);
  }
};

const nextPage = () => {
  if (hasNext.value) {
    page.value++;
  }
};

const previousPage = () => {
  if (hasPrevious.value) {
    page.value--;
  }
};

const goToPage = (pageNum: number) => {
  page.value = pageNum;
};

const refresh = () => {
  loadDetectors();
};

const clearError = () => {
  error.value = null;
};

const formatDate = (dateString: string) => {
  return new Date(dateString).toLocaleDateString();
};

// Watchers
watch([page, () => props.filters], () => {
  loadDetectors();
});

// Lifecycle
onMounted(() => {
  loadDetectors();
});
</script>

<style scoped>
/* Add your component styles here */
.pynomaly-detector-list {
  /* Component styles */
}

.error-container {
  padding: 20px;
  background-color: #fee;
  border: 1px solid #fcc;
  border-radius: 4px;
}

.loading-container {
  text-align: center;
  padding: 40px;
}

.loading-spinner {
  width: 40px;
  height: 40px;
  border: 4px solid #f3f3f3;
  border-top: 4px solid #3498db;
  border-radius: 50%;
  animation: spin 1s linear infinite;
  margin: 0 auto 20px;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.detector-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 20px;
  margin: 20px 0;
}

.detector-card {
  padding: 20px;
  border: 1px solid #ddd;
  border-radius: 8px;
  cursor: pointer;
  transition: all 0.2s ease;
}

.detector-card:hover {
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
}

.pagination {
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 10px;
  margin: 20px 0;
}

.pagination-btn, .page-btn {
  padding: 8px 16px;
  border: 1px solid #ddd;
  background: white;
  cursor: pointer;
  border-radius: 4px;
}

.page-btn.active {
  background: #3498db;
  color: white;
  border-color: #3498db;
}
</style>

// src/packages/sdk/pynomaly-js-sdk/src/components/DetectorList.tsx
/**
 * Detector List Component
 * 
 * React component for displaying and managing a list of anomaly detectors
 * with pagination, filtering, and selection capabilities.
 */

import React, { useMemo } from 'react';
import { DetectorListProps } from '../types';
import { PynomalyClient } from '../core/client';
import { useDetectorList } from '../hooks/useDetector';

/**
 * Detector list component with built-in pagination and filtering.
 * 
 * @param props Component properties
 * @returns JSX element
 */
export const DetectorList: React.FC<DetectorListProps & { client: PynomalyClient }> = ({
  client,
  onDetectorSelect,
  filters,
  pageSize = 20,
  className = ''
}) => {
  const {
    detectors,
    total,
    page,
    hasNext,
    hasPrevious,
    isLoading,
    error,
    nextPage,
    previousPage,
    goToPage,
    refresh,
    clearError
  } = useDetectorList(client, {
    algorithmName: filters?.algorithmName,
    tags: filters?.tags,
    pageSize,
    autoLoad: true
  });

  // Calculate page numbers for pagination
  const pageNumbers = useMemo(() => {
    const totalPages = Math.ceil(total / pageSize);
    const current = page;
    const delta = 2; // Number of pages to show on each side of current page
    
    const pages: number[] = [];
    const start = Math.max(1, current - delta);
    const end = Math.min(totalPages, current + delta);
    
    for (let i = start; i <= end; i++) {
      pages.push(i);
    }
    
    return pages;
  }, [total, pageSize, page]);

  // Handle detector click
  const handleDetectorClick = (detector: any) => {
    if (onDetectorSelect) {
      onDetectorSelect(detector);
    }
  };

  // Error display
  if (error) {
    return (
      <div className={`pynomaly-detector-list ${className}`}>
        <div className="error-container">
          <div className="error-message">
            <h3>Error Loading Detectors</h3>
            <p>{error.message}</p>
            <div className="error-actions">
              <button onClick={clearError} className="btn-secondary">
                Dismiss
              </button>
              <button onClick={() => refresh()} className="btn-primary">
                Retry
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className={`pynomaly-detector-list ${className}`}>
      {/* Header */}
      <div className="detector-list-header">
        <div className="header-info">
          <h2>Detectors</h2>
          <span className="total-count">{total} total</span>
        </div>
        <div className="header-actions">
          <button 
            onClick={() => refresh()} 
            disabled={isLoading}
            className="btn-secondary"
          >
            {isLoading ? 'Loading...' : 'Refresh'}
          </button>
        </div>
      </div>

      {/* Filters */}
      {filters && (
        <div className="detector-filters">
          {filters.algorithmName && (
            <span className="filter-tag">
              Algorithm: {filters.algorithmName}
            </span>
          )}
          {filters.tags?.map(tag => (
            <span key={tag} className="filter-tag">
              Tag: {tag}
            </span>
          ))}
        </div>
      )}

      {/* Loading State */}
      {isLoading && detectors.length === 0 && (
        <div className="loading-container">
          <div className="loading-spinner"></div>
          <p>Loading detectors...</p>
        </div>
      )}

      {/* Empty State */}
      {!isLoading && detectors.length === 0 && (
        <div className="empty-state">
          <div className="empty-icon">🔍</div>
          <h3>No Detectors Found</h3>
          <p>
            {filters ? 
              'No detectors match your current filters.' : 
              'No detectors have been created yet.'
            }
          </p>
        </div>
      )}

      {/* Detector Grid */}
      {detectors.length > 0 && (
        <>
          <div className="detector-grid">
            {detectors.map((detector) => (
              <div
                key={detector.id}
                className="detector-card"
                onClick={() => handleDetectorClick(detector)}
                role="button"
                tabIndex={0}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' || e.key === ' ') {
                    handleDetectorClick(detector);
                  }
                }}
              >
                <div className="detector-header">
                  <h3 className="detector-name">{detector.name}</h3>
                  <span className={`detector-status ${detector.is_fitted ? 'trained' : 'untrained'}`}>
                    {detector.is_fitted ? 'Trained' : 'Untrained'}
                  </span>
                </div>
                
                <div className="detector-info">
                  <div className="info-item">
                    <label>Algorithm:</label>
                    <span>{detector.algorithm_name}</span>
                  </div>
                  <div className="info-item">
                    <label>Contamination Rate:</label>
                    <span>{(detector.contamination_rate * 100).toFixed(1)}%</span>
                  </div>
                  {detector.description && (
                    <div className="info-item">
                      <label>Description:</label>
                      <span className="description">{detector.description}</span>
                    </div>
                  )}
                </div>

                {detector.tags && detector.tags.length > 0 && (
                  <div className="detector-tags">
                    {detector.tags.map((tag: string) => (
                      <span key={tag} className="tag">{tag}</span>
                    ))}
                  </div>
                )}

                <div className="detector-meta">
                  <span className="created-date">
                    Created: {new Date(detector.created_at).toLocaleDateString()}
                  </span>
                </div>
              </div>
            ))}
          </div>

          {/* Pagination */}
          {total > pageSize && (
            <div className="pagination">
              <button
                onClick={previousPage}
                disabled={!hasPrevious || isLoading}
                className="pagination-btn"
              >
                Previous
              </button>

              <div className="page-numbers">
                {pageNumbers.map((pageNum) => (
                  <button
                    key={pageNum}
                    onClick={() => goToPage(pageNum)}
                    disabled={isLoading}
                    className={`page-btn ${pageNum === page ? 'active' : ''}`}
                  >
                    {pageNum}
                  </button>
                ))}
              </div>

              <button
                onClick={nextPage}
                disabled={!hasNext || isLoading}
                className="pagination-btn"
              >
                Next
              </button>
            </div>
          )}

          {/* Page Info */}
          <div className="page-info">
            Showing {Math.min((page - 1) * pageSize + 1, total)} to{' '}
            {Math.min(page * pageSize, total)} of {total} detectors
          </div>
        </>
      )}
    </div>
  );
};

/**
 * Simplified detector list component for basic use cases.
 * 
 * @param props Component properties
 * @returns JSX element
 */
export const SimpleDetectorList: React.FC<{
  client: PynomalyClient;
  onSelect?: (detector: any) => void;
  className?: string;
}> = ({ client, onSelect, className = '' }) => {
  const { detectors, isLoading, error } = useDetectorList(client, {
    pageSize: 50,
    autoLoad: true
  });

  if (isLoading) {
    return (
      <div className={`pynomaly-simple-detector-list ${className}`}>
        <div className="loading">Loading detectors...</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className={`pynomaly-simple-detector-list ${className}`}>
        <div className="error">Error: {error.message}</div>
      </div>
    );
  }

  return (
    <div className={`pynomaly-simple-detector-list ${className}`}>
      <select 
        onChange={(e) => {
          const detector = detectors.find(d => d.id === e.target.value);
          if (detector && onSelect) {
            onSelect(detector);
          }
        }}
        className="detector-select"
      >
        <option value="">Select a detector...</option>
        {detectors.map((detector) => (
          <option key={detector.id} value={detector.id}>
            {detector.name} ({detector.algorithm_name})
          </option>
        ))}
      </select>
    </div>
  );
};
