// src/templates/client_sdks/typescript/examples/angular-example.ts
/**
 * Angular Example: anomaly_detection SDK Integration
 * Demonstrates how to use the anomaly_detection TypeScript SDK in Angular applications
 */

import { Component, OnInit, OnDestroy, Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { BehaviorSubject, Observable, Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

import { AnomalyDetectionClient } from '../src/index';
import {
  DetectionRequest,
  DetectionResponse,
  StreamDetectionResult,
  StreamAlert,
  HealthStatus,
  LoginCredentials,
  UserProfile,
} from '../src/types';

// Angular Service for anomaly_detection SDK
@Injectable({
  providedIn: 'root'
})
export class anomaly-detectionService {
  private client: AnomalyDetectionClient;
  private isAuthenticatedSubject = new BehaviorSubject<boolean>(false);
  private userProfileSubject = new BehaviorSubject<UserProfile | null>(null);
  private isConnectedSubject = new BehaviorSubject<boolean>(false);
  private streamDataSubject = new BehaviorSubject<StreamDetectionResult[]>([]);
  private alertsSubject = new BehaviorSubject<StreamAlert[]>([]);
  private healthStatusSubject = new BehaviorSubject<HealthStatus | null>(null);

  public isAuthenticated$ = this.isAuthenticatedSubject.asObservable();
  public userProfile$ = this.userProfileSubject.asObservable();
  public isConnected$ = this.isConnectedSubject.asObservable();
  public streamData$ = this.streamDataSubject.asObservable();
  public alerts$ = this.alertsSubject.asObservable();
  public healthStatus$ = this.healthStatusSubject.asObservable();

  constructor() {
    this.client = new AnomalyDetectionClient({
      baseUrl: process.env['NG_APP_ANOMALY_DETECTION_API_URL'] || 'https://api.anomaly_detection.com',
      apiKey: process.env['NG_APP_ANOMALY_DETECTION_API_KEY'],
      debug: process.env['NODE_ENV'] === 'development',
      websocket: {
        enabled: true,
        autoReconnect: true,
      },
    });

    // Check initial authentication state
    this.checkAuthenticationState();
  }

  private checkAuthenticationState(): void {
    const clientInfo = this.client.getClientInfo();
    this.isAuthenticatedSubject.next(clientInfo.isAuthenticated);
    this.userProfileSubject.next(clientInfo.sessionInfo || null);
    this.isConnectedSubject.next(clientInfo.isConnected);
  }

  async login(credentials: LoginCredentials): Promise<{ token: any; user: UserProfile }> {
    const response = await this.client.auth.login(credentials);
    this.isAuthenticatedSubject.next(true);
    this.userProfileSubject.next(response.user);
    return response;
  }

  async logout(): Promise<void> {
    await this.client.auth.logout();
    this.isAuthenticatedSubject.next(false);
    this.userProfileSubject.next(null);
    this.isConnectedSubject.next(false);
  }

  async detectAnomalies(request: DetectionRequest): Promise<DetectionResponse> {
    return await this.client.detection.detect(request);
  }

  async connectWebSocket(): Promise<void> {
    await this.client.connectWebSocket({
      onConnect: () => {
        this.isConnectedSubject.next(true);
        console.log('WebSocket connected');
      },
      onDisconnect: () => {
        this.isConnectedSubject.next(false);
        console.log('WebSocket disconnected');
      },
      onData: (data: StreamDetectionResult) => {
        const currentData = this.streamDataSubject.value;
        this.streamDataSubject.next([...currentData.slice(-19), data]);
      },
      onAlert: (alert: StreamAlert) => {
        const currentAlerts = this.alertsSubject.value;
        this.alertsSubject.next([...currentAlerts.slice(-9), alert]);
      },
      onError: (error: Error) => {
        console.error('WebSocket error:', error);
      },
    });
  }

  disconnectWebSocket(): void {
    this.client.disconnectWebSocket();
    this.isConnectedSubject.next(false);
  }

  async sendTestData(): Promise<void> {
    const streamingManager = this.client.getStreamingManager();
    if (!streamingManager) return;

    const data = Array.from({ length: 10 }, () => Math.random() * 100);
    await streamingManager.sendStreamData('test-stream', data);
  }

  async getHealth(): Promise<HealthStatus> {
    const health = await this.client.health.getHealth();
    this.healthStatusSubject.next(health);
    return health;
  }

  getClient(): AnomalyDetectionClient {
    return this.client;
  }
}

// Authentication Component
@Component({
  selector: 'app-anomaly_detection-auth',
  template: `
    <div class="auth-container">
      <div *ngIf="isAuthenticated$ | async; else loginForm">
        <h2>Welcome, {{ (userProfile$ | async)?.username }}!</h2>
        <button 
          (click)="logout()" 
          [disabled]="loading"
          class="btn btn-danger">
          {{ loading ? 'Logging out...' : 'Logout' }}
        </button>
      </div>
      
      <ng-template #loginForm>
        <form (ngSubmit)="login()" #authForm="ngForm">
          <h2>Login to anomaly_detection</h2>
          
          <div class="form-group">
            <label>Username:</label>
            <input
              type="text"
              [(ngModel)]="credentials.username"
              name="username"
              required
              class="form-control"
            />
          </div>

          <div class="form-group">
            <label>Password:</label>
            <input
              type="password"
              [(ngModel)]="credentials.password"
              name="password"
              required
              class="form-control"
            />
          </div>

          <div class="form-group">
            <label>MFA Code (optional):</label>
            <input
              type="text"
              [(ngModel)]="credentials.mfaCode"
              name="mfaCode"
              class="form-control"
            />
          </div>

          <button 
            type="submit" 
            [disabled]="loading || !authForm.form.valid"
            class="btn btn-primary">
            {{ loading ? 'Logging in...' : 'Login' }}
          </button>
        </form>
      </ng-template>

      <div *ngIf="error" class="alert alert-danger">
        {{ error }}
      </div>
    </div>
  `,
  styles: [`
    .auth-container {
      padding: 20px;
      max-width: 400px;
      margin: 0 auto;
    }
    
    .form-group {
      margin-bottom: 15px;
    }
    
    .form-group label {
      display: block;
      margin-bottom: 5px;
      font-weight: bold;
    }
    
    .form-control {
      width: 100%;
      padding: 8px;
      border: 1px solid #ddd;
      border-radius: 4px;
      box-sizing: border-box;
    }
    
    .btn {
      padding: 10px 20px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      font-size: 14px;
    }
    
    .btn-primary {
      background-color: #007bff;
      color: white;
    }
    
    .btn-danger {
      background-color: #dc3545;
      color: white;
    }
    
    .btn:disabled {
      opacity: 0.6;
      cursor: not-allowed;
    }
    
    .alert {
      padding: 10px;
      border-radius: 4px;
      margin: 10px 0;
    }
    
    .alert-danger {
      background-color: #f8d7da;
      color: #721c24;
      border: 1px solid #f5c6cb;
    }
  `]
})
export class anomaly-detectionAuthComponent implements OnInit, OnDestroy {
  private destroy$ = new Subject<void>();

  isAuthenticated$: Observable<boolean>;
  userProfile$: Observable<UserProfile | null>;
  loading = false;
  error: string | null = null;

  credentials: LoginCredentials = {
    username: '',
    password: '',
    mfaCode: '',
  };

  constructor(private anomaly-detectionService: anomaly-detectionService) {
    this.isAuthenticated$ = this.anomaly-detectionService.isAuthenticated$;
    this.userProfile$ = this.anomaly-detectionService.userProfile$;
  }

  ngOnInit(): void {}

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  async login(): Promise<void> {
    this.loading = true;
    this.error = null;

    try {
      await this.anomaly-detectionService.login(this.credentials);
    } catch (err: any) {
      this.error = err.message || 'Login failed';
    } finally {
      this.loading = false;
    }
  }

  async logout(): Promise<void> {
    this.loading = true;
    try {
      await this.anomaly-detectionService.logout();
    } catch (err: any) {
      this.error = err.message || 'Logout failed';
    } finally {
      this.loading = false;
    }
  }
}

// Anomaly Detection Component
@Component({
  selector: 'app-anomaly_detection-detection',
  template: `
    <div class="detection-container">
      <h2>Anomaly Detection</h2>
      
      <div class="form-group">
        <label>Input Data (comma-separated):</label>
        <input
          type="text"
          [(ngModel)]="inputData"
          placeholder="1,2,3,4,5,100,6,7,8,9"
          class="form-control"
        />
      </div>

      <div class="form-group">
        <label>Algorithm:</label>
        <select [(ngModel)]="algorithm" class="form-control">
          <option value="isolation_forest">Isolation Forest</option>
          <option value="one_class_svm">One-Class SVM</option>
          <option value="local_outlier_factor">Local Outlier Factor</option>
          <option value="elliptic_envelope">Elliptic Envelope</option>
        </select>
      </div>

      <button 
        (click)="detectAnomalies()" 
        [disabled]="loading"
        class="btn btn-primary">
        {{ loading ? 'Detecting...' : 'Detect Anomalies' }}
      </button>

      <div *ngIf="error" class="alert alert-danger">
        {{ error }}
      </div>

      <div *ngIf="result" class="results">
        <h3>Results</h3>
        <div class="result-item">
          <strong>Anomaly Rate:</strong> {{ (result.anomalyRate * 100).toFixed(2) }}%
        </div>
        <div class="result-item">
          <strong>Processing Time:</strong> {{ result.processingTime }}ms
        </div>
        <div class="result-item">
          <strong>Algorithm:</strong> {{ result.algorithm }}
        </div>
        
        <h4>Scores and Predictions:</h4>
        <table class="results-table">
          <thead>
            <tr>
              <th>Index</th>
              <th>Score</th>
              <th>Prediction</th>
              <th>Confidence</th>
            </tr>
          </thead>
          <tbody>
            <tr 
              *ngFor="let score of result.scores; let i = index" 
              [class.anomaly]="result.predictions[i]">
              <td>{{ i }}</td>
              <td>{{ score.toFixed(4) }}</td>
              <td>{{ result.predictions[i] ? 'Anomaly' : 'Normal' }}</td>
              <td>{{ result.confidence[i]?.toFixed(4) || 'N/A' }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  `,
  styles: [`
    .detection-container {
      padding: 20px;
    }
    
    .form-group {
      margin-bottom: 15px;
    }
    
    .form-group label {
      display: block;
      margin-bottom: 5px;
      font-weight: bold;
    }
    
    .form-control {
      width: 100%;
      padding: 8px;
      border: 1px solid #ddd;
      border-radius: 4px;
      box-sizing: border-box;
    }
    
    .btn {
      padding: 10px 20px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      font-size: 14px;
    }
    
    .btn-primary {
      background-color: #007bff;
      color: white;
    }
    
    .btn:disabled {
      opacity: 0.6;
      cursor: not-allowed;
    }
    
    .alert {
      padding: 10px;
      border-radius: 4px;
      margin: 10px 0;
    }
    
    .alert-danger {
      background-color: #f8d7da;
      color: #721c24;
      border: 1px solid #f5c6cb;
    }
    
    .results {
      margin-top: 20px;
      padding: 20px;
      border: 1px solid #ddd;
      border-radius: 4px;
      background-color: #f8f9fa;
    }
    
    .result-item {
      margin-bottom: 10px;
    }
    
    .results-table {
      width: 100%;
      border-collapse: collapse;
      margin: 10px 0;
    }
    
    .results-table th,
    .results-table td {
      border: 1px solid #ddd;
      padding: 8px;
      text-align: left;
    }
    
    .results-table th {
      background-color: #f2f2f2;
      font-weight: bold;
    }
    
    .results-table tr.anomaly {
      background-color: #ffe6e6;
    }
  `]
})
export class anomaly-detectionDetectionComponent implements OnInit, OnDestroy {
  private destroy$ = new Subject<void>();

  inputData = '1,2,3,4,5,100,6,7,8,9';
  algorithm = 'isolation_forest';
  result: DetectionResponse | null = null;
  loading = false;
  error: string | null = null;

  constructor(private anomaly-detectionService: anomaly-detectionService) {}

  ngOnInit(): void {}

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  async detectAnomalies(): Promise<void> {
    this.loading = true;
    this.error = null;

    try {
      const data = this.inputData.split(',').map(Number);
      
      const request: DetectionRequest = {
        data,
        algorithm: this.algorithm as any,
        parameters: {
          contamination: 0.1,
          n_estimators: 100,
        },
        includeExplanations: true,
      };

      this.result = await this.anomaly-detectionService.detectAnomalies(request);
    } catch (err: any) {
      this.error = err.message || 'Detection failed';
    } finally {
      this.loading = false;
    }
  }
}

// Streaming Component
@Component({
  selector: 'app-anomaly_detection-streaming',
  template: `
    <div class="streaming-container">
      <h2>Real-time Streaming</h2>
      
      <div class="controls">
        <button 
          *ngIf="!(isConnected$ | async)" 
          (click)="connectWebSocket()" 
          [disabled]="loading"
          class="btn btn-primary">
          {{ loading ? 'Connecting...' : 'Connect WebSocket' }}
        </button>
        
        <ng-container *ngIf="isConnected$ | async">
          <button (click)="disconnectWebSocket()" class="btn btn-danger">
            Disconnect
          </button>
          <button (click)="sendTestData()" class="btn btn-secondary">
            Send Test Data
          </button>
        </ng-container>
      </div>

      <div class="status">
        Status: {{ (isConnected$ | async) ? '🟢 Connected' : '🔴 Disconnected' }}
      </div>

      <div *ngIf="error" class="alert alert-danger">
        {{ error }}
      </div>

      <div *ngIf="(alerts$ | async)?.length" class="alerts">
        <h3>Recent Alerts</h3>
        <div 
          *ngFor="let alert of alerts$ | async" 
          [class]="'alert alert-' + alert.level">
          <strong>{{ alert.level.toUpperCase() }}:</strong> {{ alert.message }}
          <span class="score">Score: {{ alert.score.toFixed(4) }}</span>
        </div>
      </div>

      <div *ngIf="(streamData$ | async)?.length" class="stream-data">
        <h3>Real-time Results</h3>
        <div class="data-grid">
          <div *ngFor="let data of streamData$ | async" class="data-item">
            <div>Stream: {{ data.streamId }}</div>
            <div>Anomalies: {{ data.result.anomalyRate.toFixed(2) }}%</div>
            <div>Time: {{ formatTime(data.timestamp) }}</div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .streaming-container {
      padding: 20px;
    }
    
    .controls {
      margin-bottom: 20px;
      display: flex;
      gap: 10px;
    }
    
    .btn {
      padding: 10px 20px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      font-size: 14px;
    }
    
    .btn-primary {
      background-color: #007bff;
      color: white;
    }
    
    .btn-danger {
      background-color: #dc3545;
      color: white;
    }
    
    .btn-secondary {
      background-color: #6c757d;
      color: white;
    }
    
    .btn:disabled {
      opacity: 0.6;
      cursor: not-allowed;
    }
    
    .status {
      font-size: 16px;
      font-weight: bold;
      margin-bottom: 20px;
    }
    
    .alert {
      padding: 10px;
      margin: 5px 0;
      border-radius: 4px;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    
    .alert-info {
      background-color: #d1ecf1;
      color: #0c5460;
    }
    
    .alert-warning {
      background-color: #fff3cd;
      color: #856404;
    }
    
    .alert-critical {
      background-color: #f8d7da;
      color: #721c24;
    }
    
    .score {
      font-size: 12px;
      opacity: 0.8;
    }
    
    .stream-data {
      margin-top: 20px;
    }
    
    .data-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
      gap: 10px;
      margin: 10px 0;
    }
    
    .data-item {
      border: 1px solid #ddd;
      padding: 10px;
      border-radius: 4px;
      background-color: #f8f9fa;
    }
  `]
})
export class anomaly-detectionStreamingComponent implements OnInit, OnDestroy {
  private destroy$ = new Subject<void>();

  isConnected$: Observable<boolean>;
  streamData$: Observable<StreamDetectionResult[]>;
  alerts$: Observable<StreamAlert[]>;
  loading = false;
  error: string | null = null;

  constructor(private anomaly-detectionService: anomaly-detectionService) {
    this.isConnected$ = this.anomaly-detectionService.isConnected$;
    this.streamData$ = this.anomaly-detectionService.streamData$;
    this.alerts$ = this.anomaly-detectionService.alerts$;
  }

  ngOnInit(): void {}

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  async connectWebSocket(): Promise<void> {
    this.loading = true;
    this.error = null;

    try {
      await this.anomaly-detectionService.connectWebSocket();
    } catch (err: any) {
      this.error = err.message || 'Connection failed';
    } finally {
      this.loading = false;
    }
  }

  disconnectWebSocket(): void {
    this.anomaly-detectionService.disconnectWebSocket();
  }

  async sendTestData(): Promise<void> {
    try {
      await this.anomaly-detectionService.sendTestData();
    } catch (err: any) {
      this.error = err.message || 'Failed to send data';
    }
  }

  formatTime(timestamp: number): string {
    return new Date(timestamp).toLocaleTimeString();
  }
}

// Health Component
@Component({
  selector: 'app-anomaly_detection-health',
  template: `
    <div class="health-container">
      <h2>System Health</h2>
      
      <div class="controls">
        <button 
          (click)="fetchHealth()" 
          [disabled]="loading"
          class="btn btn-primary">
          {{ loading ? 'Refreshing...' : 'Refresh' }}
        </button>
        
        <label class="checkbox-label">
          <input 
            type="checkbox" 
            [(ngModel)]="autoRefresh"
            (change)="onAutoRefreshChange()"
          />
          Auto-refresh (5s)
        </label>
      </div>

      <div *ngIf="error" class="alert alert-danger">
        {{ error }}
      </div>

      <div *ngIf="healthStatus$ | async as health" class="health-status">
        <div [class]="'overall-status status-' + health.status">
          <h3>Overall Status: {{ health.status.toUpperCase() }}</h3>
          <div>Version: {{ health.version }}</div>
          <div>Uptime: {{ formatUptime(health.uptime) }}</div>
        </div>

        <div class="services">
          <h4>Services</h4>
          <div 
            *ngFor="let service of health.services" 
            [class]="'service status-' + service.status">
            <strong>{{ service.name }}</strong>
            <span class="status">{{ service.status }}</span>
            <span *ngIf="service.responseTime" class="response-time">
              {{ service.responseTime }}ms
            </span>
            <div *ngIf="service.error" class="service-error">
              {{ service.error }}
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .health-container {
      padding: 20px;
    }
    
    .controls {
      margin-bottom: 20px;
      display: flex;
      align-items: center;
      gap: 15px;
    }
    
    .btn {
      padding: 10px 20px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      font-size: 14px;
    }
    
    .btn-primary {
      background-color: #007bff;
      color: white;
    }
    
    .btn:disabled {
      opacity: 0.6;
      cursor: not-allowed;
    }
    
    .checkbox-label {
      display: flex;
      align-items: center;
      gap: 5px;
    }
    
    .alert {
      padding: 10px;
      border-radius: 4px;
      margin: 10px 0;
    }
    
    .alert-danger {
      background-color: #f8d7da;
      color: #721c24;
      border: 1px solid #f5c6cb;
    }
    
    .health-status {
      margin-top: 20px;
    }
    
    .overall-status {
      padding: 20px;
      border-radius: 8px;
      margin-bottom: 20px;
    }
    
    .overall-status.status-healthy {
      background-color: #d4edda;
      border: 1px solid #c3e6cb;
    }
    
    .overall-status.status-degraded {
      background-color: #fff3cd;
      border: 1px solid #ffeaa7;
    }
    
    .overall-status.status-unhealthy {
      background-color: #f8d7da;
      border: 1px solid #f5c6cb;
    }
    
    .services {
      margin-top: 20px;
    }
    
    .service {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 10px;
      margin: 5px 0;
      border: 1px solid #ddd;
      border-radius: 4px;
      background-color: white;
    }
    
    .service-error {
      color: #dc3545;
      font-size: 12px;
      flex-basis: 100%;
      margin-top: 5px;
    }
    
    .response-time {
      font-size: 12px;
      opacity: 0.7;
    }
    
    .status-healthy { color: #28a745; }
    .status-degraded { color: #ffc107; }
    .status-unhealthy { color: #dc3545; }
  `]
})
export class anomaly-detectionHealthComponent implements OnInit, OnDestroy {
  private destroy$ = new Subject<void>();
  private refreshInterval: any;

  healthStatus$: Observable<HealthStatus | null>;
  loading = false;
  error: string | null = null;
  autoRefresh = false;

  constructor(private anomaly-detectionService: anomaly-detectionService) {
    this.healthStatus$ = this.anomaly-detectionService.healthStatus$;
  }

  ngOnInit(): void {
    this.fetchHealth();
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
    if (this.refreshInterval) {
      clearInterval(this.refreshInterval);
    }
  }

  async fetchHealth(): Promise<void> {
    this.loading = true;
    this.error = null;

    try {
      await this.anomaly-detectionService.getHealth();
    } catch (err: any) {
      this.error = err.message || 'Failed to fetch health status';
    } finally {
      this.loading = false;
    }
  }

  onAutoRefreshChange(): void {
    if (this.refreshInterval) {
      clearInterval(this.refreshInterval);
      this.refreshInterval = null;
    }

    if (this.autoRefresh) {
      this.refreshInterval = setInterval(() => {
        this.fetchHealth();
      }, 5000);
    }
  }

  formatUptime(uptime: number): string {
    const hours = Math.floor(uptime / 3600);
    const minutes = Math.floor((uptime % 3600) / 60);
    return `${hours}h ${minutes}m`;
  }
}

// Main Application Component
@Component({
  selector: 'app-anomaly_detection-main',
  template: `
    <div class="anomaly_detection-app">
      <header>
        <h1>anomaly_detection Angular Example</h1>
        <nav>
          <button 
            *ngFor="let tab of tabs" 
            [class.active]="activeTab === tab.id"
            (click)="activeTab = tab.id"
            class="nav-button">
            {{ tab.label }}
          </button>
        </nav>
      </header>

      <main>
        <app-anomaly_detection-auth *ngIf="activeTab === 'auth'"></app-anomaly_detection-auth>
        <app-anomaly_detection-detection *ngIf="activeTab === 'detection'"></app-anomaly_detection-detection>
        <app-anomaly_detection-streaming *ngIf="activeTab === 'streaming'"></app-anomaly_detection-streaming>
        <app-anomaly_detection-health *ngIf="activeTab === 'health'"></app-anomaly_detection-health>
      </main>
    </div>
  `,
  styles: [`
    .anomaly_detection-app {
      max-width: 1200px;
      margin: 0 auto;
      padding: 20px;
      font-family: Arial, sans-serif;
    }
    
    header {
      border-bottom: 2px solid #eee;
      margin-bottom: 20px;
      padding-bottom: 20px;
    }
    
    nav {
      display: flex;
      gap: 10px;
      margin-top: 15px;
    }
    
    .nav-button {
      padding: 10px 20px;
      border: 1px solid #ddd;
      background: white;
      cursor: pointer;
      border-radius: 4px;
      font-size: 14px;
    }
    
    .nav-button:hover {
      background: #f8f9fa;
    }
    
    .nav-button.active {
      background: #007bff;
      color: white;
    }
    
    .nav-button.active:hover {
      background: #0056b3;
    }
  `]
})
export class anomaly-detectionMainComponent {
  activeTab = 'auth';

  tabs = [
    { id: 'auth', label: 'Authentication' },
    { id: 'detection', label: 'Anomaly Detection' },
    { id: 'streaming', label: 'Real-time Streaming' },
    { id: 'health', label: 'System Health' },
  ];
}

// Angular Module
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { HttpClientModule } from '@angular/common/http';
import { FormsModule } from '@angular/forms';

@NgModule({
  declarations: [
    anomaly-detectionMainComponent,
    anomaly-detectionAuthComponent,
    anomaly-detectionDetectionComponent,
    anomaly-detectionStreamingComponent,
    anomaly-detectionHealthComponent,
  ],
  imports: [
    BrowserModule,
    HttpClientModule,
    FormsModule,
  ],
  providers: [
    anomaly-detectionService,
  ],
  bootstrap: [anomaly-detectionMainComponent]
})
export class anomaly-detectionModule { }

// Export all components for use in other modules
export {
  anomaly-detectionService,
  anomaly-detectionMainComponent,
  anomaly-detectionAuthComponent,
  anomaly-detectionDetectionComponent,
  anomaly-detectionStreamingComponent,
  anomaly-detectionHealthComponent,
  anomaly-detectionModule,
};

// src/templates/client_sdks/typescript/examples/vue-example.vue
<template>
  <div class="anomaly_detection-app">
    <header>
      <h1>anomaly_detection Vue.js Example</h1>
      <nav>
        <button
          v-for="tab in tabs"
          :key="tab.id"
          :class="{ active: activeTab === tab.id }"
          @click="activeTab = tab.id"
        >
          {{ tab.label }}
        </button>
      </nav>
    </header>

    <main>
      <!-- Authentication Section -->
      <div v-if="activeTab === 'auth'" class="auth-container">
        <div v-if="isAuthenticated">
          <h2>Welcome, {{ user?.username }}!</h2>
          <button @click="logout" :disabled="loading">
            {{ loading ? 'Logging out...' : 'Logout' }}
          </button>
        </div>
        <form v-else @submit.prevent="login">
          <h2>Login to anomaly_detection</h2>
          
          <div>
            <label>Username:</label>
            <input
              v-model="credentials.username"
              type="text"
              required
            />
          </div>

          <div>
            <label>Password:</label>
            <input
              v-model="credentials.password"
              type="password"
              required
            />
          </div>

          <div>
            <label>MFA Code (optional):</label>
            <input
              v-model="credentials.mfaCode"
              type="text"
            />
          </div>

          <button type="submit" :disabled="loading">
            {{ loading ? 'Logging in...' : 'Login' }}
          </button>
        </form>
      </div>

      <!-- Anomaly Detection Section -->
      <div v-if="activeTab === 'detection'" class="detection-container">
        <h2>Anomaly Detection</h2>
        
        <div>
          <label>Input Data (comma-separated):</label>
          <input
            v-model="inputData"
            type="text"
            placeholder="1,2,3,4,5,100,6,7,8,9"
          />
        </div>

        <div>
          <label>Algorithm:</label>
          <select v-model="algorithm">
            <option value="isolation_forest">Isolation Forest</option>
            <option value="one_class_svm">One-Class SVM</option>
            <option value="local_outlier_factor">Local Outlier Factor</option>
            <option value="elliptic_envelope">Elliptic Envelope</option>
          </select>
        </div>

        <button @click="detectAnomalies" :disabled="loading">
          {{ loading ? 'Detecting...' : 'Detect Anomalies' }}
        </button>

        <div v-if="detectionResult" class="results">
          <h3>Results</h3>
          <div>
            <strong>Anomaly Rate:</strong> {{ (detectionResult.anomalyRate * 100).toFixed(2) }}%
          </div>
          <div>
            <strong>Processing Time:</strong> {{ detectionResult.processingTime }}ms
          </div>
          <div>
            <strong>Algorithm:</strong> {{ detectionResult.algorithm }}
          </div>
          
          <h4>Scores and Predictions:</h4>
          <table>
            <thead>
              <tr>
                <th>Index</th>
                <th>Score</th>
                <th>Prediction</th>
                <th>Confidence</th>
              </tr>
            </thead>
            <tbody>
              <tr
                v-for="(score, index) in detectionResult.scores"
                :key="index"
                :class="{ anomaly: detectionResult.predictions[index] }"
              >
                <td>{{ index }}</td>
                <td>{{ score.toFixed(4) }}</td>
                <td>{{ detectionResult.predictions[index] ? 'Anomaly' : 'Normal' }}</td>
                <td>{{ detectionResult.confidence[index]?.toFixed(4) || 'N/A' }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <!-- Streaming Section -->
      <div v-if="activeTab === 'streaming'" class="streaming-container">
        <h2>Real-time Streaming</h2>
        
        <div class="controls">
          <button v-if="!isConnected" @click="connectWebSocket" :disabled="loading">
            {{ loading ? 'Connecting...' : 'Connect WebSocket' }}
          </button>
          <template v-else>
            <button @click="disconnectWebSocket">Disconnect</button>
            <button @click="sendTestData">Send Test Data</button>
          </template>
        </div>

        <div class="status">
          Status: {{ isConnected ? '🟢 Connected' : '🔴 Disconnected' }}
        </div>

        <div v-if="alerts.length > 0" class="alerts">
          <h3>Recent Alerts</h3>
          <div
            v-for="(alert, index) in alerts"
            :key="index"
            :class="`alert alert-${alert.level}`"
          >
            <strong>{{ alert.level.toUpperCase() }}:</strong> {{ alert.message }}
            <span class="score">Score: {{ alert.score.toFixed(4) }}</span>
          </div>
        </div>

        <div v-if="streamData.length > 0" class="stream-data">
          <h3>Real-time Results</h3>
          <div class="data-grid">
            <div
              v-for="(data, index) in streamData"
              :key="index"
              class="data-item"
            >
              <div>Stream: {{ data.streamId }}</div>
              <div>Anomalies: {{ data.result.anomalyRate.toFixed(2) }}%</div>
              <div>Time: {{ formatTime(data.timestamp) }}</div>
            </div>
          </div>
        </div>
      </div>

      <!-- Health Section -->
      <div v-if="activeTab === 'health'" class="health-container">
        <h2>System Health</h2>
        
        <div class="controls">
          <button @click="fetchHealth" :disabled="loading">
            {{ loading ? 'Refreshing...' : 'Refresh' }}
          </button>
          <label>
            <input
              v-model="autoRefresh"
              type="checkbox"
            />
            Auto-refresh (5s)
          </label>
        </div>

        <div v-if="health" class="health-status">
          <div :class="`overall-status status-${health.status}`">
            <h3>Overall Status: {{ health.status.toUpperCase() }}</h3>
            <div>Version: {{ health.version }}</div>
            <div>Uptime: {{ formatUptime(health.uptime) }}</div>
          </div>

          <div class="services">
            <h4>Services</h4>
            <div
              v-for="(service, index) in health.services"
              :key="index"
              :class="`service status-${service.status}`"
            >
              <strong>{{ service.name }}</strong>
              <span class="status">{{ service.status }}</span>
              <span v-if="service.responseTime" class="response-time">
                {{ service.responseTime }}ms
              </span>
              <div v-if="service.error" class="service-error">
                {{ service.error }}
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Error Display -->
      <div v-if="error" class="error">
        {{ error }}
      </div>
    </main>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, computed, onMounted, onUnmounted, watch } from 'vue';
import { AnomalyDetectionClient } from '../src/index';
import type {
  DetectionRequest,
  DetectionResponse,
  StreamDetectionResult,
  StreamAlert,
  HealthStatus,
  UserProfile,
} from '../src/types';

// Reactive state
const activeTab = ref('auth');
const loading = ref(false);
const error = ref<string | null>(null);

// Authentication state
const isAuthenticated = ref(false);
const user = ref<UserProfile | null>(null);
const credentials = reactive({
  username: '',
  password: '',
  mfaCode: '',
});

// Detection state
const inputData = ref('1,2,3,4,5,100,6,7,8,9');
const algorithm = ref('isolation_forest');
const detectionResult = ref<DetectionResponse | null>(null);

// Streaming state
const isConnected = ref(false);
const streamData = ref<StreamDetectionResult[]>([]);
const alerts = ref<StreamAlert[]>([]);

// Health state
const health = ref<HealthStatus | null>(null);
const autoRefresh = ref(false);

// Client instance
const client = new AnomalyDetectionClient({
  baseUrl: import.meta.env.VITE_ANOMALY_DETECTION_API_URL || 'https://api.anomaly_detection.com',
  apiKey: import.meta.env.VITE_ANOMALY_DETECTION_API_KEY,
  debug: import.meta.env.DEV,
  websocket: {
    enabled: true,
    autoReconnect: true,
  },
});

// Tab configuration
const tabs = [
  { id: 'auth', label: 'Authentication' },
  { id: 'detection', label: 'Anomaly Detection' },
  { id: 'streaming', label: 'Real-time Streaming' },
  { id: 'health', label: 'System Health' },
];

// Authentication methods
const login = async () => {
  loading.value = true;
  error.value = null;

  try {
    const response = await client.auth.login(credentials);
    isAuthenticated.value = true;
    user.value = response.user;
  } catch (err: any) {
    error.value = err.message || 'Login failed';
  } finally {
    loading.value = false;
  }
};

const logout = async () => {
  loading.value = true;
  try {
    await client.auth.logout();
    isAuthenticated.value = false;
    user.value = null;
  } catch (err: any) {
    error.value = err.message || 'Logout failed';
  } finally {
    loading.value = false;
  }
};

// Detection methods
const detectAnomalies = async () => {
  loading.value = true;
  error.value = null;

  try {
    const data = inputData.value.split(',').map(Number);
    
    const request: DetectionRequest = {
      data,
      algorithm: algorithm.value as any,
      parameters: {
        contamination: 0.1,
        n_estimators: 100,
      },
      includeExplanations: true,
    };

    detectionResult.value = await client.detection.detect(request);
  } catch (err: any) {
    error.value = err.message || 'Detection failed';
  } finally {
    loading.value = false;
  }
};

// Streaming methods
const connectWebSocket = async () => {
  loading.value = true;
  error.value = null;

  try {
    await client.connectWebSocket({
      onConnect: () => {
        isConnected.value = true;
        console.log('WebSocket connected');
      },
      onDisconnect: () => {
        isConnected.value = false;
        console.log('WebSocket disconnected');
      },
      onData: (data: StreamDetectionResult) => {
        streamData.value = [...streamData.value.slice(-19), data];
      },
      onAlert: (alert: StreamAlert) => {
        alerts.value = [...alerts.value.slice(-9), alert];
      },
      onError: (wsError: Error) => {
        error.value = wsError.message;
      },
    });
  } catch (err: any) {
    error.value = err.message || 'Connection failed';
  } finally {
    loading.value = false;
  }
};

const disconnectWebSocket = () => {
  client.disconnectWebSocket();
  isConnected.value = false;
};

const sendTestData = async () => {
  if (!isConnected.value) return;

  try {
    const streamingManager = client.getStreamingManager();
    if (!streamingManager) return;

    const data = Array.from({ length: 10 }, () => Math.random() * 100);
    await streamingManager.sendStreamData('test-stream', data);
  } catch (err: any) {
    error.value = err.message || 'Failed to send data';
  }
};

// Health methods
const fetchHealth = async () => {
  loading.value = true;
  error.value = null;

  try {
    health.value = await client.health.getHealth();
  } catch (err: any) {
    error.value = err.message || 'Failed to fetch health status';
  } finally {
    loading.value = false;
  }
};

// Utility functions
const formatTime = (timestamp: number) => {
  return new Date(timestamp).toLocaleTimeString();
};

const formatUptime = (uptime: number) => {
  const hours = Math.floor(uptime / 3600);
  const minutes = Math.floor((uptime % 3600) / 60);
  return `${hours}h ${minutes}m`;
};

// Lifecycle hooks
onMounted(() => {
  // Check if already authenticated
  const clientInfo = client.getClientInfo();
  isAuthenticated.value = clientInfo.isAuthenticated;
  user.value = clientInfo.sessionInfo || null;

  // Fetch initial health status
  fetchHealth();
});

// Auto-refresh health status
let healthInterval: NodeJS.Timeout | null = null;

watch(autoRefresh, (newValue) => {
  if (healthInterval) {
    clearInterval(healthInterval);
    healthInterval = null;
  }

  if (newValue) {
    healthInterval = setInterval(fetchHealth, 5000);
  }
});

onUnmounted(() => {
  if (healthInterval) {
    clearInterval(healthInterval);
  }
  client.disconnectWebSocket();
});
</script>

<style scoped>
.anomaly_detection-app {
  max-width: 1200px;
  margin: 0 auto;
  padding: 20px;
  font-family: Arial, sans-serif;
}

header {
  border-bottom: 2px solid #eee;
  margin-bottom: 20px;
  padding-bottom: 20px;
}

nav button {
  margin-right: 10px;
  padding: 10px 20px;
  border: 1px solid #ddd;
  background: white;
  cursor: pointer;
  border-radius: 4px;
}

nav button.active {
  background: #007bff;
  color: white;
}

nav button:hover {
  background: #f8f9fa;
}

nav button.active:hover {
  background: #0056b3;
}

.error {
  color: #dc3545;
  background: #f8d7da;
  padding: 10px;
  border-radius: 4px;
  margin: 10px 0;
  border: 1px solid #f5c6cb;
}

.auth-container,
.detection-container,
.streaming-container,
.health-container {
  padding: 20px;
}

.auth-container form div,
.detection-container div {
  margin-bottom: 15px;
}

.auth-container label,
.detection-container label {
  display: block;
  margin-bottom: 5px;
  font-weight: bold;
}

.auth-container input,
.detection-container input,
.detection-container select {
  width: 100%;
  padding: 8px;
  border: 1px solid #ddd;
  border-radius: 4px;
  box-sizing: border-box;
}

button {
  padding: 10px 20px;
  border: 1px solid #007bff;
  background: #007bff;
  color: white;
  border-radius: 4px;
  cursor: pointer;
  margin-right: 10px;
}

button:hover {
  background: #0056b3;
}

button:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.controls {
  margin-bottom: 20px;
  display: flex;
  align-items: center;
  gap: 15px;
}

.status {
  font-size: 16px;
  font-weight: bold;
  margin-bottom: 20px;
}

.status-healthy { color: #28a745; }
.status-degraded { color: #ffc107; }
.status-unhealthy { color: #dc3545; }

.alerts {
  margin-bottom: 20px;
}

.alert {
  padding: 10px;
  margin: 5px 0;
  border-radius: 4px;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.alert-info { background: #d1ecf1; color: #0c5460; }
.alert-warning { background: #fff3cd; color: #856404; }
.alert-critical { background: #f8d7da; color: #721c24; }

.score {
  font-size: 12px;
  opacity: 0.8;
}

.stream-data {
  margin-top: 20px;
}

.data-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
  gap: 10px;
  margin: 10px 0;
}

.data-item {
  border: 1px solid #ddd;
  padding: 10px;
  border-radius: 4px;
  background: #f8f9fa;
}

.results {
  margin-top: 20px;
  padding: 20px;
  border: 1px solid #ddd;
  border-radius: 4px;
  background: #f8f9fa;
}

table {
  width: 100%;
  border-collapse: collapse;
  margin: 10px 0;
}

th, td {
  border: 1px solid #ddd;
  padding: 8px;
  text-align: left;
}

th {
  background: #f2f2f2;
  font-weight: bold;
}

tr.anomaly {
  background-color: #ffe6e6;
}

.health-status {
  margin-top: 20px;
}

.overall-status {
  padding: 20px;
  border-radius: 8px;
  margin-bottom: 20px;
}

.overall-status.status-healthy {
  background: #d4edda;
  border: 1px solid #c3e6cb;
}

.overall-status.status-degraded {
  background: #fff3cd;
  border: 1px solid #ffeaa7;
}

.overall-status.status-unhealthy {
  background: #f8d7da;
  border: 1px solid #f5c6cb;
}

.services {
  margin-top: 20px;
}

.service {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 10px;
  margin: 5px 0;
  border: 1px solid #ddd;
  border-radius: 4px;
  background: white;
}

.service-error {
  color: #dc3545;
  font-size: 12px;
  flex-basis: 100%;
  margin-top: 5px;
}

.response-time {
  font-size: 12px;
  opacity: 0.7;
}
</style>
